# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `curdle` gem.
# Please instead update this file by running `bin/tapioca gem curdle`.


# source://curdle//lib/curdle.rb#3
module Curdle
  class << self
    # source://curdle//lib/curdle.rb#12
    def process(code, filename = T.unsafe(nil)); end

    # source://curdle//lib/curdle.rb#7
    def process_file(file); end
  end
end

# source://curdle//lib/curdle/remove_sorbet.rb#4
class Curdle::RemoveSorbet < ::Parser::TreeRewriter
  # source://curdle//lib/curdle/remove_sorbet.rb#15
  def on_block(node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#25
  def on_casgn(node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#20
  def on_ivasgn(node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#5
  def on_send(node); end

  private

  # source://curdle//lib/curdle/remove_sorbet.rb#197
  def comment_out_node(node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#205
  def include_leading_whitespace(location); end

  # this isn't used anywhere but it was so hard to write I'm keeping it in case
  # I ever need to use it again
  #
  # source://curdle//lib/curdle/remove_sorbet.rb#213
  def include_trailing_whitespace(location); end

  # source://curdle//lib/curdle/remove_sorbet.rb#72
  def remove_abstract_bang(send_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#191
  def remove_all_but_first_arg(send_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#81
  def remove_cast(send_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#35
  def remove_extend(send_node, const_str); end

  # source://curdle//lib/curdle/remove_sorbet.rb#109
  def remove_let(asgn_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#178
  def remove_method_call(send_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#91
  def remove_must(send_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#49
  def remove_sig(block_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#61
  def remove_t_send(send_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#165
  def remove_type_alias(casgn_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#143
  def remove_type_member(casgn_node); end

  # source://curdle//lib/curdle/remove_sorbet.rb#100
  def remove_unsafe(send_node); end
end

# source://curdle//lib/curdle/tasks.rb#2
module Curdle::Tasks
  extend ::FileUtils::StreamUtils_
  extend ::FileUtils
  extend ::Rake::FileUtilsExt
  extend ::Rake::DSL

  class << self
    # source://curdle//lib/curdle/tasks.rb#6
    def install(gemspec_file = T.unsafe(nil)); end

    private

    # source://curdle//lib/curdle/tasks.rb#44
    def find_gemspec; end
  end
end
