# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `curdle` gem.
# Please instead update this file by running `bin/tapioca gem curdle`.

module Curdle
  class << self
    def process(code, filename = T.unsafe(nil)); end
    def process_file(file); end
  end
end

class Curdle::RemoveSorbet < ::Parser::TreeRewriter
  def on_block(node); end
  def on_casgn(node); end
  def on_ivasgn(node); end
  def on_send(node); end

  private

  def comment_out_node(node); end
  def include_leading_whitespace(location); end
  def include_trailing_whitespace(location); end
  def remove_abstract_bang(send_node); end
  def remove_all_but_first_arg(send_node); end
  def remove_cast(send_node); end
  def remove_extend(send_node, const_str); end
  def remove_let(asgn_node); end
  def remove_method_call(send_node); end
  def remove_must(send_node); end
  def remove_sig(block_node); end
  def remove_t_send(send_node); end
  def remove_type_alias(casgn_node); end
  def remove_type_member(casgn_node); end
  def remove_unsafe(send_node); end
end

module Curdle::Tasks
  extend ::FileUtils::StreamUtils_
  extend ::FileUtils
  extend ::Rake::FileUtilsExt
  extend ::Rake::DSL

  class << self
    def install(gemspec_file = T.unsafe(nil)); end

    private

    def find_gemspec; end
  end
end
