# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ffi-compiler/all/ffi-compiler.rbi
#
# ffi-compiler-1.0.1

module FFI::Compiler
end
class FFI::Compiler::Platform
  def arch; end
  def mac?; end
  def map_library_name(name); end
  def name; end
  def os; end
  def self.system; end
end
module FFI
end
module FFI::Compiler::Loader
  def self.caller_path(line = nil); end
  def self.find(name, start_path = nil); end
end
