# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/helm-rb-0.2.1-x86_64/all/helm-rb-0.2.1-x86_64.rbi
#
# helm-rb-0.2.1-x86_64-darwin

module HelmRb
  def self.executable; end
end
