# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `helm-cli` gem.
# Please instead update this file by running `bin/tapioca gem helm-cli`.

class HelmCLI
  def initialize(kubeconfig_path, executable = T.unsafe(nil)); end

  def add_repo(name, url); end
  def executable; end
  def get_release(release, namespace: T.unsafe(nil)); end
  def install_chart(chart, release:, version:, namespace: T.unsafe(nil), params: T.unsafe(nil)); end
  def kubeconfig_path; end
  def last_status; end
  def release_exists?(release, namespace: T.unsafe(nil)); end
  def stderr; end
  def stderr=(new_stderr); end
  def stdout; end
  def stdout=(new_stdout); end
  def update_repos; end
  def upgrade_chart(chart, release:, version:, namespace: T.unsafe(nil), params: T.unsafe(nil)); end
  def with_pipes(out = T.unsafe(nil), err = T.unsafe(nil)); end

  private

  def backticks(cmd); end
  def base_cmd; end
  def last_status=(status); end
  def status_key; end
  def stderr_key; end
  def stdout_key; end
  def systemm(cmd); end
end

class HelmCLI::HelmError < ::StandardError; end
class HelmCLI::InstallError < ::HelmCLI::HelmError; end
class HelmCLI::MissingReleaseError < ::HelmCLI::HelmError; end
class HelmCLI::UpgradeError < ::HelmCLI::HelmError; end
