# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/helm-cli/all/helm-cli.rbi
#
# helm-cli-0.3.0

class HelmCLI
  def add_repo(name, url); end
  def backticks(cmd); end
  def base_cmd; end
  def executable; end
  def get_release(release, namespace: nil); end
  def initialize(kubeconfig_path, executable = nil); end
  def install_chart(chart, release:, version:, namespace: nil, params: nil); end
  def kubeconfig_path; end
  def last_status; end
  def last_status=(status); end
  def release_exists?(release, namespace: nil); end
  def status_key; end
  def stderr; end
  def stderr=(new_stderr); end
  def stderr_key; end
  def stdout; end
  def stdout=(new_stdout); end
  def stdout_key; end
  def systemm(cmd); end
  def update_repos; end
  def upgrade_chart(chart, release:, version:, namespace: nil, params: nil); end
  def with_pipes(out = nil, err = nil); end
end
class HelmCLI::HelmError < StandardError
end
class HelmCLI::MissingReleaseError < HelmCLI::HelmError
end
class HelmCLI::InstallError < HelmCLI::HelmError
end
class HelmCLI::UpgradeError < HelmCLI::HelmError
end
