# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kubernetes-cli/all/kubernetes-cli.rbi
#
# kubernetes-cli-0.3.1

class KubernetesCLI
  def after_execute(&block); end
  def annotate(type, namespace, name, annotations, overwrite: nil); end
  def api_resources; end
  def apply(res, dry_run: nil); end
  def apply_uri(uri, dry_run: nil); end
  def backticks(cmd); end
  def backticks_default(cmd); end
  def backticks_open3(cmd); end
  def base_cmd; end
  def before_execute(&block); end
  def current_context; end
  def env; end
  def exec_cmd(container_cmd, namespace, pod, tty = nil); end
  def execc(cmd); end
  def executable; end
  def get_object(type, namespace, name = nil, match_labels = nil); end
  def get_objects(type, namespace, match_labels = nil); end
  def initialize(kubeconfig_path, executable = nil); end
  def kubeconfig_path; end
  def last_status; end
  def last_status=(status); end
  def logtail(namespace, selector, follow: nil); end
  def open3_w(env, cmd, opts = nil, &block); end
  def restart_deployment(namespace, deployment); end
  def run_after_callbacks(cmd); end
  def run_before_callbacks(cmd); end
  def run_cmd(cmd); end
  def stderr; end
  def stderr=(new_stderr); end
  def stdout; end
  def stdout=(new_stdout); end
  def system_cmd(container_cmd, namespace, pod, tty = nil); end
  def systemm(cmd); end
  def systemm_default(cmd); end
  def systemm_open3(cmd); end
  def with_pipes(out = nil, err = nil); end
end
class KubernetesCLI::KubernetesError < StandardError
end
class KubernetesCLI::InvalidResourceError < KubernetesCLI::KubernetesError
  def resource; end
  def resource=(arg0); end
end
class KubernetesCLI::InvalidResourceUriError < KubernetesCLI::KubernetesError
  def resource_uri; end
  def resource_uri=(arg0); end
end
class KubernetesCLI::GetResourceError < KubernetesCLI::KubernetesError
end
