# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kubectl-rb` gem.
# Please instead update this file by running `bin/tapioca gem kubectl-rb`.

module KubectlRb
  class << self
    def executable; end
  end
end

KubectlRb::KUBECTL_VERSION = T.let(T.unsafe(nil), String)
KubectlRb::VERSION = T.let(T.unsafe(nil), String)
