# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/to_regexp/all/to_regexp.rbi
#
# to_regexp-0.2.1

module ToRegexp
end
module ToRegexp::Regexp
  def to_regexp; end
end
module ToRegexp::String
  def as_regexp(options = nil); end
  def self.literal?(str); end
  def to_regexp(options = nil); end
end
class String
  include ToRegexp::String
end
class Regexp
  include ToRegexp::Regexp
end
